export enum Branch {
    AURA = "AURA",
    DEFENSE = "DEFENSE",
    FORTIFICATION = "FORTIFICATION",
    EMISSION = "EMISSION",
    TRANSMUTATION = "TRANSMUTATION",
    MANIPULATION = "MANIPULATION",
    SUPPORT = "SUPPORT",
    SPECIFIC = "SPECIFIC"
}